### ISSUE TITLE
.

### ISSUE THREAD

**Issue by elliotberry** [delucis/load-nextstep-plist#2]
Just wanted to say I enjoyed your TypeError sassiness, this is not an issue
![Screen Shot 2022-10-18 at 4 34 07 PM](https://user-images.githubusercontent.com/9747139/196538474-dd977e6c-de3d-44b5-ad4d-5af1f5d1291e.png)

**Comment by delucis** [comment]
Haha — wish I could claim credit! That’s in the `nextstep-plist` dependency: <https://www.npmjs.com/package/nextstep-plist>

Glad you enjoyed it nonetheless ;-)
